server:
  port: 0

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:ecom;
    driver-class-name: org.h2.Driver
    username: sa

  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

greeting:
  message: welcome very wlecome user-service
logging:
  level:
    com.example.userservice.client: DEBUG

#token:
#  expiration_time: 86400000
#  secret: user_token123
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

