server:
  port: 8888

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/bw/soma
#
#  profiles:
#    active: default
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
